### ISSUE TITLE
Playground unlikely to work with multi-org and endorsement policy

### ISSUE THREAD

**Issue by davidkel** [davidkel/fc#20]
will work with single org
probably work with multi-org and no endorsement policy, but what would happen exactly ?
- install: No problem here
- start: Start will probably work as the default instantiation policy only requires single endorsement
- upgrade: Same as start
- transaction: peers don't endorse if they don't have the right chaincode and version
- query: not an issue as sent only to single peer.

**Comment by davidkel** [comment]
Multi-org no endorsement policy
```
2018-04-04 13:33:12.265 UTC [lscc] executeDeployOrUpgrade -> ERRO 039 cannot get package for chaincode (basic-sample-network:0.2.3-20180326082813)-err:open /var/hyperledger/production/chaincodes/basic-sample-network.0.2.3-20180326082813: no such file or directory
2018-04-04 13:33:12.265 UTC [endorser] ProcessProposal -> ERRO 03a [composerchannel][12e7591c] simulateProposal() resulted in chaincode name:"lscc"  response status 500 for txid: 12e7591cd3766a8be587ca02cd2f030ab6d8c9c9c88a350614d7d6598f4d1bba
2018-04-04 13:33:15.262 UTC [couchdb] CreateDatabaseIfNotExist -> INFO 03b Created state database composerchannel_lscc
2018-04-04 13:33:15.303 UTC [couchdb] CreateDatabaseIfNotExist -> INFO 03c Created state database composerchannel_basic-sample-network
2018-04-04 13:33:15.329 UTC [cceventmgmt] HandleStateUpdates -> INFO 03d Channel [composerchannel]: Handling LSCC state update for chaincode [basic-sample-network]
2018-04-04 13:33:15.329 UTC [ccprovider] ExtractStatedbArtifactsForChaincode -> INFO 03e Error while loading installation package for ccname=%s, ccversion=%s. Err=%s basic-sample-network 0.2.3-20180326082813 open /var/hyperledger/production/chaincodes/basic-sample-network.0.2.3-20180326082813: no such file or directory
2018-04-04 13:33:15.329 UTC [cceventmgmt] HandleChaincodeDeploy -> INFO 03f Channel [composerchannel]: Chaincode [Name=basic-sample-network, Version=0.2.3-20180326082813, Hash=[]byte{0xab, 0x7a, 0xf4, 0x86, 0x67, 0x52, 0x5b, 0xde, 0xad, 0xe, 0x61, 0x32, 0x1c, 0xc9, 0x4f, 0xfd, 0x19, 0x96, 0x80, 0xa2, 0xdf, 0xb2, 0xb8, 0x56, 0x51, 0x2f, 0x70, 0x8e, 0x6f, 0x9d, 0xd6, 0xd9}] is not installed hence no need to create chaincode artifacts for endorsement
2018-04-04 13:33:15.332 UTC [kvledger] CommitWithPvtData -> INFO 040 Channel [composerchannel]: Committed block [1] with 1 transaction(s)
2018-04-04 13:34:36.615 UTC [kvledger] CommitWithPvtData -> INFO 041 Channel [composerchannel]: Committed block [2] with 1 transaction(s)
2018-04-04 13:35:50.049 UTC [lscc] executeDeployOrUpgrade -> ERRO 042 cannot get package for chaincode (basic-sample-network:0.2.3-deploy.0)-err:open /var/hyperledger/production/chaincodes/basic-sample-network.0.2.3-deploy.0: no such file or directory
2018-04-04 13:35:50.049 UTC [endorser] ProcessProposal -> ERRO 043 [composerchannel][7bce5acb] simulateProposal() resulted in chaincode name:"lscc"  response status 500 for txid: 7bce5acb097fc9e5410604eb8a9f4434bba5a595ae5da7cdadb1a7cd62c08d77
2018-04-04 13:35:52.406 UTC [committer/txvalidator] validateTx -> INFO 044 Find chaincode upgrade transaction for chaincode basic-sample-network on channel composerchannel with new version 0.2.3-deploy.0
2018-04-04 13:35:52.447 UTC [cceventmgmt] HandleStateUpdates -> INFO 045 Channel [composerchannel]: Handling LSCC state update for chaincode [basic-sample-network]
2018-04-04 13:35:52.447 UTC [ccprovider] ExtractStatedbArtifactsForChaincode -> INFO 046 Error while loading installation package for ccname=%s, ccversion=%s. Err=%s basic-sample-network 0.2.3-deploy.0 open /var/hyperledger/production/chaincodes/basic-sample-network.0.2.3-deploy.0: no such file or directory
2018-04-04 13:35:52.447 UTC [cceventmgmt] HandleChaincodeDeploy -> INFO 047 Channel [composerchannel]: Chaincode [Name=basic-sample-network, Version=0.2.3-deploy.0, Hash=[]byte{0xf6, 0xe2, 0x67, 0x12, 0x9d, 0x2a, 0xb7, 0xf8, 0xe7, 0x0, 0xef, 0x44, 0xe3, 0x39, 0x53, 0x21, 0x32, 0x58, 0x60, 0x7f, 0xbb, 0x24, 0x48, 0x76, 0x4, 0xa0, 0xe1, 0x3c, 0x7d, 0x63, 0xde, 0xf6}] is not installed hence no need to create chaincode artifacts for endorsement
2018-04-04 13:35:52.450 UTC [kvledger] CommitWithPvtData -> INFO 048 Channel [composerchannel]: Committed block [3] with 1 transaction(s)
2018-04-04 13:38:03.225 UTC [kvledger] CommitWithPvtData -> INFO 049 Channel [composerchannel]: Committed block [4] with 1 transaction(s)
2018-04-04 13:38:03.262 UTC [common/deliver] deliverBlocks -> WARN 04a [channel: composerchannel] Error sending to 172.19.0.1:56000: rpc error: code = Unknown desc = the stream has been done

2018-04-04 13:38:38.512 UTC [kvledger] CommitWithPvtData -> INFO 04b Channel [composerchannel]: Committed block [5] with 1 transaction(s)



2018-04-04 13:39:53.633 UTC [kvledger] CommitWithPvtData -> INFO 04c Channel [composerchannel]: Committed block [6] with 1 transaction(s)
```
basically the peer doesn't act as an endorser, so only ever send 1 endorsement back

**Comment by davidkel** [comment]
on transaction submission do get this, but not logged to the peer which is strange
```
error: [Hyperledger-Composer] undefined:HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: cannot retrieve package for chaincode basic-sample-network/0.2.3-deploy.0, error open /var/hyperledger/production/chaincodes/basic-sample-network.0.2.3-deploy.0: no such file or directory
    at new createStatusError (/home/vagrant/19.0/node_modules/grpc/src/client.js:64:15)
    at /home/vagrant/19.0/node_modules/grpc/src/client.js:583:15
warn: [Hyperledger-Composer] undefined:HLFConnection            :Response from attempted p
```

**Comment by davidkel** [comment]
alternative is to document this.
