### ISSUE TITLE
Error reported at startup, should not affect chaincode listener registration though.

### ISSUE THREAD

**Issue by davidkel** [davidkel/fc#73]
```
Zachs-Air:perishable-network Zach$ composer-rest-server -c admin@perishable-network -n never -w true

Discovering types from business network definition ...
/Users/Zach/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/ChannelEventHub.js:666
				throw error;
				^

Error: Connection is not in the READY state
    at ChannelEventHub._checkConnection (/Users/Zach/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/ChannelEventHub.js:664:17)
    at ChannelEventHub.registerChaincodeEvent (/Users/Zach/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/ChannelEventHub.js:825:8)
    at HLFConnection._registerForChaincodeEvents (/Users/Zach/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:279:44)
    at HLFConnection._checkCCListener (/Users/Zach/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:256:22)
    at Timeout.ccListenerHandle.setTimeout [as _onTimeout] (/Users/Zach/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:381:35)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by davidkel** [comment]
Damn GRPC breaking changes
